# Generated by Django 4.0.2 on 2022-02-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm', models.CharField(max_length=50)),
                ('total_areas', models.IntegerField()),
                ('geo', models.CharField(max_length=50)),
                ('total_plants', models.IntegerField()),
            ],
        ),
    ]
